### ISSUE TITLE
Auto Complete Test Issue

### ISSUE THREAD

**Issue by dylanapplegate** [J-Graham/Urgent-Fury#5]
I'm getting an issue when trying to run the TestAutoComplete.html file locally. First, it appears that the comment in the head is appearing when just trying to load the page:

![image](https://cloud.githubusercontent.com/assets/8238179/6995927/22a496dc-db36-11e4-8f80-4c8257616f9e.png)

As well, I'm getting the following javscript error

```
Uncaught ReferenceError: mockArray is not defined
```

I'm using Chrome Version 41.0.2272.118 (64-bit) on a Mac.

**Comment by coconaut** [comment]
Noticed the whole style section, among other lines, were completely missing from last merge. Appear to be correct this time.

``` html
<style>
```

###### Markdown!!!!

**Comment by dylanapplegate** [comment]
I think this is a bit stale, so I'm closing it haha.

**Comment by J-Graham** [comment]
Understandable, I was about to submit a merge request today though :D.
